### ISSUE TITLE
Cannot install current version (0.0.8) with pip install sphinx-markdown-tables

### ISSUE THREAD

**Issue by johncrossland** [ryanfox/sphinx-markdown-tables#13]
Should I install an earlier version from: https://pypi.org/project/sphinx-markdown-tables/#history ?

See the attached screenshot of the error I get running pip install sphinx-markdown-tables for 0.0.8

![cannot_pip_install_sphinx-markdown-tables](https://user-images.githubusercontent.com/24421729/44500868-db7aaa80-a6de-11e8-8aa8-41492dad5778.png)

`Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-VVCrfn/sphinx-markdown-tables/`

sphinx-markdown-tables worked for HTML output (end-June) but I cannot install it now (end-Aug).

**Comment by johncrossland** [comment]
I successfully installed an earlier version (0.0.3) with a pip install sphinx-markdown-tables==0.0.3

![used_pip_install_sphinx-markdown-tables 0 0 3_successfully](https://user-images.githubusercontent.com/24421729/44501459-6361b400-a6e1-11e8-93c7-54acab9bca43.png)

I'm running Python 3.5.2 and sphinx-markdown-tables 0.0.3 works with it fine. I'll update my build script to run pip install sphinx-markdown-tables==0.0.3 to keep my build system portable between new VMs.

**Comment by ryanfox** [comment]
Couple things:

You're likely installing the package into python 2 - root's default `pip` is almost certainly python 2. You need to `pip3 install ...` to install in python 3. There was an issue with circular imports in python 2 - my guess is that is what you're seeing.

That said, it's probably a bad idea to pip install as root. A virtual environment works well for this kind of thing, and [pipenv](https://pipenv.readthedocs.io/en/latest/) is designed for it.

Finally, the issue should be fixed in v0.0.9 regardless.
