### ISSUE TITLE
I cant bundle image inside table.

### ISSUE THREAD

**Issue by mikkame** [ryanfox/sphinx-markdown-tables#20]
If I write a link to the image in the table, the image will not be copied to the build.

**Comment by ryanfox** [comment]
An example would be useful. What syntax are you using?

**Comment by moose-x86** [comment]
Hi, 
I have same issue.

| Proxy types                                                                          |
| ------------------------------------------------------------------------- |
|  ![img](assets/reverse-proxy-02-1.jpg)                                |
|      ![test](assets/reverse-proxy-01-1.jpg)                            |


Sphinx only shows names in square braces.

**Comment by htleeab** [comment]
I also have same issue.
The image filepath in html is the filepath inside the brackets (e.g. "img/xxx.png"), while it should be "/_images/xxx.png"

**Comment by ryanfox** [comment]
I've taken a couple cracks at this, unfortunately I think it's inherent to using a markdown implementation that's not supported by sphinx. Here's what's happening:

`markdown` takes in markdown (with tables) and replaces it with HTML. Since `markdown` doesn't have sphinx's context, it won't convert e.g. image links inside those tables properly.

At a later step in the build process, `recommonmark` sees an html table inside a markdown file, and includes it verbatim. This is expected - you are supposed to be able to include arbitrary html inside a markdown file.

Instead of running `markdown` before sphinx parses everything with `recommonmark`, what if we do it after? 

Unfortunately this doesn't work either, because `recommonmark` doesn't leave the tables alone. Blocks that `recommonmark` doesn't recognize get wrapped in `<problematic></problematic>` tags. So if we use `markdown` to locate and parse the tables after that, it sees HTML and won't process it. Again, this is expected.

So if we use `markdown` before sphinx parses everything, we get broken links. If we use `markdown` after, no tables get processed period.

There's always the option of writing your links in html to begin with. I know it's not ideal, but it is a workaround.

I looked at extending `CommonMarkParser` to fix it and ended up going down a bit of a rabbit hole, it doesn't look like that is a feasible route to me. If anyone can come up with a fix, I am happy to review a PR.
